
project_id = "nywmylszhzifqovfnbva"

[functions.newsletter-confirm]
verify_jwt = false

[functions.newsletter-send-confirmation]
verify_jwt = false

[functions.newsletter-unsubscribe]
verify_jwt = false

[functions.newsletter-send]
verify_jwt = false
