
project_id = "aggkhetcdjmggqjzelgd"

[functions.newsletter-send]
verify_jwt = true

[functions.newsletter-confirm]
verify_jwt = false

[functions.newsletter-send-confirmation]
verify_jwt = false

[functions.newsletter-unsubscribe]
verify_jwt = false

[functions.newsletter-send-email]
verify_jwt = true
